version: '3'
services:
  backend:
    image: maven:3.9.6-eclipse-temurin-17
    volumes:
      - ../exam:/usr/local/app
      - ./mnt/.m2:/root/.m2
    ports:
      - 8080:8080
    logging:
      options:
        max-size: "10k"
        max-file: "3"
    working_dir: /usr/local/app
    command: "mvn clean spring-boot:run"